/**
 * P2 plugin step execution (apps/runner side).
 *
 * Flow:
 * 1. `runTest` (run.ts) loads the trusted registry via
 *    `@playwright-studio/action-sdk` (`loadPluginsFromDir`, gated on
 *    `ALLOW_PLUGINS=1`) when the definition contains `plugin:*` steps.
 * 2. `materializePlugins()` copies the plugin entry files into the isolated
 *    workdir (`plugins/`, deterministic sorted layout) and writes the static
 *    `vv-plugins.cjs` shim below; the generated spec calls
 *    `runPluginStep(type, params, page, { stepId })`.
 * 3. The shim resolves the type from `VV_PLUGINS` (JSON type -> { file,
 *    schema }), validates params (required/unknown/secret-literal — same
 *    rules as the SDK), and invokes `execute({ page, params, stepId, env })`.
 * 4. Unknown type -> explicit `PLUGIN_NOT_FOUND` (never a silent skip).
 *
 * Security: plugin files are trusted Dev/Admin code copied verbatim (no
 * sandbox — documented in the SDK). Only basenames/relative paths inside
 * `plugins/` are addressable; the shim refuses absolute paths and `..`.
 */

import { cp, mkdir, writeFile } from 'node:fs/promises';
import { basename, join, resolve, sep } from 'node:path';
import { isPluginsEnabled, loadPluginsFromDir, type LoadedPlugins } from '@playwright-studio/action-sdk';
import type { PluginCompileInfo } from './compile.js';

export class PluginExecutionError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'PluginExecutionError';
  }
}

/**
 * Static workdir shim (plain CJS, no dependencies beyond node builtins).
 * It must stay dependency-free: the isolated workdir resolves modules only
 * via the runner-injected NODE_PATH, so the shim itself requires nothing.
 */
export const PLUGIN_SHIM_CJS = `'use strict';
// Generated by @playwright-studio/runner (materializePlugins) — do not edit.
// Resolves plugin:* steps from VV_PLUGINS (JSON type -> { file, schema }).
const path = require('node:path');

function fail(code, message) {
  const err = new Error(code + ': ' + message);
  err.code = code;
  throw err;
}

function effectiveParams(stepType, rawParams, schema) {
  const rec = rawParams && typeof rawParams === 'object' && !Array.isArray(rawParams) ? rawParams : {};
  const props = (schema && schema.properties) || {};
  const out = {};
  for (const key of Object.keys(rec)) {
    if (!Object.prototype.hasOwnProperty.call(props, key)) {
      fail('PLUGIN_PARAM_INVALID', 'step "' + stepType + '" passes undeclared param "' + key + '"');
    }
    if (typeof rec[key] !== 'string') {
      fail('PLUGIN_PARAM_INVALID', 'step "' + stepType + '" param "' + key + '" must be a string');
    }
    out[key] = rec[key];
  }
  for (const key of Object.keys(props)) {
    if (out[key] === undefined) {
      const decl = props[key] || {};
      if (typeof decl.default === 'string') out[key] = decl.default;
      else if ((schema.required || []).includes(key)) {
        fail('PLUGIN_PARAM_INVALID', 'step "' + stepType + '" is missing required param "' + key + '"');
      }
    }
  }
  return out;
}

async function runPluginStep(stepType, params, page, ctx) {
  let registry;
  try {
    registry = JSON.parse(process.env.VV_PLUGINS ?? '{}');
  } catch {
    fail('PLUGIN_NOT_FOUND', 'VV_PLUGINS is not valid JSON for step "' + stepType + '"');
  }
  const entry = registry[stepType];
  if (!entry || typeof entry.file !== 'string') {
    fail(
      'PLUGIN_NOT_FOUND',
      'plugin step "' + stepType + '" is not registered (install the plugin under PLUGINS_DIR and enable with ALLOW_PLUGINS=1 after Developer/Admin review)',
    );
  }
  const rel = entry.file;
  if (path.isAbsolute(rel) || rel.split(path.sep).includes('..')) {
    fail('PLUGIN_INVALID', 'refusing to load plugin file outside plugins/ for step "' + stepType + '"');
  }
  const abs = path.join(__dirname, 'plugins', rel);
  let mod;
  try {
    mod = require(abs);
  } catch (err) {
    fail('PLUGIN_INVALID', 'cannot load plugin file for step "' + stepType + '": ' + (err && err.message ? err.message : String(err)));
  }
  const steps = Array.isArray(mod && mod.steps) ? mod.steps : [];
  const def = steps.find((s) => s && s.type === stepType);
  if (!def || typeof def.execute !== 'function') {
    fail('PLUGIN_INVALID', 'plugin file for step "' + stepType + '" does not export execute(ctx)');
  }
  const effective = effectiveParams(stepType, params, entry.schema);
  return def.execute({ page, params: effective, stepId: (ctx && ctx.stepId) || '', env: process.env });
}

module.exports = { runPluginStep };
`;

export interface MaterializedPlugins {
  /** type -> { file (workdir-relative basename), schema } — becomes VV_PLUGINS. */
  registry: Record<string, { file: string; schema?: PluginCompileInfo['schema'] }>;
}

/**
 * Load plugins (gated), copy entry files into `<workDir>/plugins/`, write the
 * shim, and return the VV_PLUGINS registry payload.
 *
 * Throws PluginExecutionError with an explicit code when plugins are disabled
 * but the definition needs them, or when a used type is not registered.
 */
export async function materializePlugins(
  workDir: string,
  stepTypes: string[],
  pluginsDir?: string,
): Promise<MaterializedPlugins> {
  if (!isPluginsEnabled()) {
    throw new PluginExecutionError(
      `PLUGIN_DISABLED: test uses plugin steps (${stepTypes.join(', ')}) but plugin loading is disabled (set ALLOW_PLUGINS=1 and have a Developer/Admin review PLUGINS_DIR first)`,
    );
  }
  let loaded: LoadedPlugins;
  try {
    loaded = await loadPluginsFromDir(pluginsDir);
  } catch (err) {
    throw new PluginExecutionError((err as Error).message);
  }
  for (const t of stepTypes) {
    if (!loaded.registry.has(t)) {
      throw new PluginExecutionError(
        `PLUGIN_NOT_FOUND: step type "${t}" is not registered (loaded: ${[...loaded.registry.keys()].join(', ') || 'none'} from ${loaded.dir})`,
      );
    }
  }
  const pluginsDest = join(workDir, 'plugins');
  await mkdir(pluginsDest, { recursive: true });
  const registry: MaterializedPlugins['registry'] = {};
  // Deterministic layout: sorted entry files, copied by basename. Plugin
  // files must be self-contained within their own directory tree entry —
  // relative requires across plugin files are resolved against the copied
  // basename (documented single-file convention in the SDK).
  const sorted = [...loaded.files].sort();
  const usedRel = new Map<string, string>();
  for (const abs of sorted) {
    const base = basename(abs);
    const dest = join(pluginsDest, base);
    // assertSafePath-equivalent: dest must stay inside pluginsDest.
    const checked = resolve(dest);
    if (checked !== resolve(pluginsDest) && !checked.startsWith(resolve(pluginsDest) + sep)) {
      throw new PluginExecutionError(`PLUGIN_INVALID: refusing to copy plugin file outside plugins/ (${base})`);
    }
    await cp(abs, dest);
    usedRel.set(abs, base);
  }
  for (const [type, { step }] of [...loaded.registry.entries()].sort(([a], [b]) => (a < b ? -1 : 1))) {
    const fileAbs = findOwnerFile(loaded, type);
    const rel = usedRel.get(fileAbs);
    if (!rel) continue;
    // Shim joins __dirname/plugins/<file>: the payload carries the basename
    // only (traversal-free; validated again inside the shim at run time).
    const sdkSchema = (step as { schema?: PluginCompileInfo['schema'] }).schema;
    registry[type] = {
      file: rel,
      ...(sdkSchema !== undefined ? { schema: sdkSchema } : {}),
    };
  }
  await writeFile(join(workDir, 'vv-plugins.cjs'), PLUGIN_SHIM_CJS, 'utf8');
  return { registry };
}

/** Owner entry file of a step type (registry values carry plugin refs). */
function findOwnerFile(loaded: LoadedPlugins, type: string): string {
  const owner = loaded.registry.get(type)?.plugin;
  if (!owner) throw new PluginExecutionError(`PLUGIN_NOT_FOUND: step type "${type}" is not registered`);
  const idx = loaded.plugins.indexOf(owner);
  const file = loaded.files[idx];
  if (!file) throw new PluginExecutionError(`PLUGIN_INVALID: no entry file for plugin "${owner.name}"`);
  return file;
}

/** Collect `plugin:*` step types from a definition (sorted, unique). */
export function collectPluginStepTypes(steps: Array<{ type: string; enabled: boolean }>): string[] {
  const out = new Set<string>();
  for (const s of steps) {
    if (s.enabled !== false && typeof s.type === 'string' && s.type.startsWith('plugin:')) out.add(s.type);
  }
  return [...out].sort();
}

// Re-export SDK surface so server routes (which already depend on the runner)
// share the canonical gate/loader without a new cross-package dependency.
export { isPluginsEnabled, loadPluginsFromDir } from '@playwright-studio/action-sdk';
export type { LoadedPlugins } from '@playwright-studio/action-sdk';
export {
  describePlugin,
  PluginLoadError,
  pluginsDir,
  validatePluginManifest,
  validatePluginParams,
} from '@playwright-studio/action-sdk';
