/**
 * AiAssistantPage — P2 AI assistant (3 tabs). Wired in App.tsx at
 * `/projects/:id/ai`, and embeddable in BuilderPage with `testId` +
 * `onInsertSteps` (insert previewed steps at the cursor).
 *
 * PROPS CONTRACT:
 *   onInsertSteps?: (steps) => void — Builder passes a callback that inserts
 *     previewed steps at the cursor. When omitted (standalone route), the
 *     "Chèn vào Builder" buttons are HIDDEN (preview-only mode).
 *   testId?: string — pre-fills the cleanup tab (cleanup-by-test).
 *   runId?: string  — pre-fills the explain tab (explain-by-run).
 *   initialTab?: 'compose' | 'explain' | 'cleanup'.
 *
 * Every server response carries `engine: 'rules' | 'llm'` and is rendered as
 * a badge — the UI never presents rule-based output as LLM output.
 */
import { useEffect, useState } from "react";
import {
  Badge,
  Button,
  DataTable,
  EmptyState,
  ErrorState,
  Field,
  Input,
  Tabs,
  Textarea,
} from "../components/ui";
import {
  aiApi,
  type AiStatus,
  type AiStep,
  type CleanupResponse,
  type ExplainResponse,
  type NlToStepsResponse,
} from "../api/ai";
import { ApiError, isNotImplemented } from "../lib/api";

export type AiTab = "compose" | "explain" | "cleanup";

export interface AiAssistantProps {
  onInsertSteps?: (steps: AiStep[]) => void;
  testId?: string;
  runId?: string;
  initialTab?: AiTab;
}

function EngineBadge({ engine }: { engine: string }) {
  return (
    <Badge tone={engine === "llm" ? "indigo" : "slate"} title={engine === "llm" ? "Generated by LLM (AI key present)" : "Local rule decision (no AI key) — not LLM"}>
      engine: {engine}
    </Badge>
  );
}

function errMsg(e: unknown): string {
  return e instanceof ApiError ? `${e.code}: ${e.message}` : e instanceof Error ? e.message : "Unknown error";
}

export function AiAssistantPage({ onInsertSteps, testId, runId, initialTab = "compose" }: AiAssistantProps) {
  const [tab, setTab] = useState<AiTab>(initialTab);
  const [status, setStatus] = useState<AiStatus | null>(null);

  useEffect(() => {
    let live = true;
    aiApi.status().then((s) => { if (live) setStatus(s); }).catch(() => { /* badge stays hidden */ });
    return () => { live = false; };
  }, []);

  return (
    <div className="mx-auto max-w-4xl space-y-4 p-4">
      <div className="flex items-center justify-between">
        <h1 className="text-lg font-semibold">AI assistant (P2 beta)</h1>
        {status ? <EngineBadge engine={status.engine} /> : null}
      </div>
      <Tabs<AiTab>
        value={tab}
        onChange={setTab}
        tabs={[
          { value: "compose", label: "Compose steps from text" },
          { value: "explain", label: "Explain failure" },
          { value: "cleanup", label: "Clean up recording" },
        ]}
      />
      {tab === "compose" ? <ComposeTab onInsertSteps={onInsertSteps} /> : null}
      {tab === "explain" ? <ExplainTab initialRunId={runId} /> : null}
      {tab === "cleanup" ? <CleanupTab testId={testId} onInsertSteps={onInsertSteps} /> : null}
    </div>
  );
}

/* ---------------------------------------------------------- compose --- */

function ComposeTab({ onInsertSteps }: { onInsertSteps?: (steps: AiStep[]) => void }) {
  const [text, setText] = useState('Open page https://example.com\nClick the "Login" button');
  const [result, setResult] = useState<NlToStepsResponse | null>(null);
  const [error, setError] = useState("");
  const [unsupported, setUnsupported] = useState(false);
  const [loading, setLoading] = useState(false);

  const run = async () => {
    setLoading(true); setError(""); setUnsupported(false);
    try {
      setResult(await aiApi.nlToSteps(text));
    } catch (e) {
      if (isNotImplemented(e)) setUnsupported(true);
      else setError(errMsg(e));
    } finally { setLoading(false); }
  };

  return (
    <div className="space-y-3">
      <Field label="Test description" hint="One idea per line. Lines the tool can't parse appear under unparsed — no steps are invented.">
        <Textarea rows={5} value={text} onChange={(e) => setText(e.target.value)} />
      </Field>
      <Button onClick={run} disabled={loading || text.trim().length === 0}>
        {loading ? "Generating…" : "Generate steps"}
      </Button>
      {unsupported ? (
        <EmptyState
          title="Backend AI not supported (API 404)"
          hint="UI is ready per contract POST /ai/nl-to-steps. Waiting on P2 backend — try again later."
        />
      ) : error ? (
        <ErrorState message={error} onRetry={run} />
      ) : null}
      {result ? (
        <div className="space-y-3">
          <div className="flex items-center gap-2">
            <EngineBadge engine={result.engine} />
            <span className="text-xs text-slate-500">{result.steps.length} steps</span>
          </div>
          <DataTable<AiStep & { id: string }>
            caption="Preview steps (unsaved — click Insert to add to Builder)"
            columns={[
              { key: "type", header: "Type", render: (r) => <code className="text-xs">{r.type}</code> },
              { key: "name", header: "Name", render: (r) => <span className="text-xs">{String(r.name ?? "—")}</span> },
              { key: "detail", header: "Details", render: (r) => <code className="text-[11px] text-slate-500">{JSON.stringify(r).slice(0, 160)}</code> },
            ]}
            rows={result.steps}
            emptyText="No steps generated — see unparsed below."
          />
          {result.unparsed.length > 0 ? (
            <div className="rounded-md border border-amber-300 bg-amber-50 p-3">
              <p className="text-xs font-semibold text-amber-800">Unparsed ({result.unparsed.length} lines — try rephrasing):</p>
              <ul className="mt-1 list-disc pl-5 text-xs text-amber-900">
                {result.unparsed.map((u, i) => <li key={i}><code>{u}</code></li>)}
              </ul>
            </div>
          ) : null}
          {onInsertSteps ? (
            <Button
              variant="secondary"
              disabled={result.steps.length === 0}
              onClick={() => onInsertSteps(result.steps)}
            >
              Insert into Builder
            </Button>
          ) : (
            <p className="text-[11px] text-slate-500">
              Preview-only — open from Builder to insert steps directly.
            </p>
          )}
        </div>
      ) : null}
      {!onInsertSteps && !result ? (
        <p className="text-[11px] text-slate-500">
          Preview-only — open from Builder to insert steps directly.
        </p>
      ) : null}
    </div>
  );
}

/* ---------------------------------------------------------- explain --- */

function ExplainTab({ initialRunId }: { initialRunId?: string }) {
  const [runId, setRunId] = useState(initialRunId ?? "");
  const [errorText, setErrorText] = useState("");
  const [stepType, setStepType] = useState("");
  const [result, setResult] = useState<ExplainResponse | null>(null);
  const [error, setError] = useState("");
  const [unsupported, setUnsupported] = useState(false);
  const [loading, setLoading] = useState(false);

  const run = async () => {
    setLoading(true); setError(""); setUnsupported(false);
    try {
      setResult(await aiApi.explain({
        ...(runId.trim() ? { runId: runId.trim() } : {}),
        ...(errorText.trim() ? { errorSummary: errorText.trim() } : {}),
        ...(stepType.trim() ? { stepType: stepType.trim() } : {}),
      }));
    } catch (e) {
      if (isNotImplemented(e)) setUnsupported(true);
      else setError(errMsg(e));
    } finally { setLoading(false); }
  };

  const exp = result?.explanation ?? null;

  return (
    <div className="space-y-3">
      <Field label="Run ID (read error from run in DB)" hint="Leave blank to paste an error manually below.">
        <Input value={runId} onChange={(e) => setRunId(e.target.value)} placeholder="run_…" />
      </Field>
      <Field label="Or paste error message">
        <Textarea rows={4} value={errorText} onChange={(e) => setErrorText(e.target.value)} placeholder="locator.click: Timeout 5000ms exceeded …" />
      </Field>
      <Field label="Step type (optional)">
        <Input value={stepType} onChange={(e) => setStepType(e.target.value)} placeholder="click" />
      </Field>
      <Button onClick={run} disabled={loading || (!runId.trim() && !errorText.trim())}>
        {loading ? "Analyzing…" : "Explain error"}
      </Button>
      {unsupported ? (
        <EmptyState
          title="Backend AI not supported (API 404)"
          hint="UI is ready per contract POST /ai/explain. Waiting on P2 backend — try again later."
        />
      ) : error ? (
        <ErrorState message={error} onRetry={run} />
      ) : null}
      {result && exp ? (
        <div className="space-y-3 rounded-lg border border-slate-200 p-3">
          <div className="flex flex-wrap items-center gap-2">
            <EngineBadge engine={result.engine} />
            <Badge tone={exp.category === "unknown" ? "amber" : "indigo"}>{exp.category}</Badge>
            <Badge tone={exp.confidence === "high" ? "green" : exp.confidence === "medium" ? "amber" : "slate"}>
              confidence: {exp.confidence}
            </Badge>
          </div>
          <p className="text-sm">{exp.summary}</p>
          <div>
            <p className="text-xs font-semibold">Likely causes:</p>
            <ul className="list-disc pl-5 text-xs">{exp.likelyCauses.map((c, i) => <li key={i}>{c}</li>)}</ul>
          </div>
          <div>
            <p className="text-xs font-semibold">Suggested fixes:</p>
            <ul className="list-disc pl-5 text-xs">{exp.suggestedFixes.map((f, i) => <li key={i}>{f}</li>)}</ul>
          </div>
        </div>
      ) : result ? null : (
        <EmptyState title="No analysis yet" hint="Enter a run ID or paste an error, then click Explain error." />
      )}
    </div>
  );
}

/* ---------------------------------------------------------- cleanup --- */

function CleanupTab({ testId, onInsertSteps }: { testId?: string; onInsertSteps?: (steps: AiStep[]) => void }) {
  const [tid, setTid] = useState(testId ?? "");
  const [rawJson, setRawJson] = useState("[\n  {\"id\": \"a\", \"type\": \"goto\", \"enabled\": true, \"url\": \"https://example.com\"}\n]");
  const [useTest, setUseTest] = useState(Boolean(testId));
  const [result, setResult] = useState<CleanupResponse | null>(null);
  const [error, setError] = useState("");
  const [unsupported, setUnsupported] = useState(false);
  const [loading, setLoading] = useState(false);

  const run = async () => {
    setLoading(true); setError(""); setUnsupported(false);
    try {
      if (useTest) {
        if (!tid.trim()) throw new Error("Enter a test ID.");
        setResult(await aiApi.cleanupByTest(tid.trim()));
      } else {
        const parsed = JSON.parse(rawJson) as unknown;
        if (!Array.isArray(parsed)) throw new Error("JSON must be an array of steps.");
        setResult(await aiApi.cleanupBySteps(parsed));
      }
    } catch (e) {
      if (isNotImplemented(e)) setUnsupported(true);
      else setError(errMsg(e));
    } finally { setLoading(false); }
  };

  return (
    <div className="space-y-3">
      <div className="flex items-center gap-2 text-xs">
        <Button variant={useTest ? "default" : "secondary"} size="sm" onClick={() => setUseTest(true)}>By test ID</Button>
        <Button variant={!useTest ? "default" : "secondary"} size="sm" onClick={() => setUseTest(false)}>Paste steps JSON</Button>
      </div>
      {useTest ? (
        <Field label="Test ID" hint="Reads steps from the saved definition. Preview only — never overwrites.">
          <Input value={tid} onChange={(e) => setTid(e.target.value)} placeholder="test_…" />
        </Field>
      ) : (
        <Field label="Raw steps JSON" hint="Raw steps array from the recorder.">
          <Textarea rows={6} value={rawJson} onChange={(e) => setRawJson(e.target.value)} />
        </Field>
      )}
      <Button onClick={run} disabled={loading}>{loading ? "Cleaning…" : "Clean recording"}</Button>
      {unsupported ? (
        <EmptyState
          title="Backend AI not supported (API 404)"
          hint="UI is ready per contract POST /ai/cleanup. Waiting on P2 backend — try again later."
        />
      ) : error ? (
        <ErrorState message={error} onRetry={run} />
      ) : null}
      {result ? (
        <div className="space-y-3">
          <div className="flex items-center gap-2">
            <EngineBadge engine={result.engine} />
            <span className="text-xs text-slate-500">{result.steps.length} steps after cleanup · {result.changes.length} changes</span>
          </div>
          <div className="rounded-lg border border-slate-200 p-3">
            <p className="text-xs font-semibold">Change log (review before saving):</p>
            <ul className="mt-1 space-y-1">
              {result.changes.map((c, i) => (
                <li key={i} className="text-xs">
                  <Badge tone={c.kind === "suggest-assertion" ? "green" : c.kind === "kept-unrecognized" ? "red" : "slate"}>{c.kind}</Badge>{" "}
                  <span>{c.description}</span>
                </li>
              ))}
            </ul>
          </div>
          <DataTable<AiStep & { id: string }>
            caption="Steps after cleanup (preview)"
            columns={[
              { key: "type", header: "Type", render: (r) => <code className="text-xs">{r.type}</code> },
              { key: "name", header: "Name", render: (r) => <span className="text-xs">{String(r.name ?? "—")}</span> },
            ]}
            rows={result.steps}
            emptyText="No steps left."
          />
          {onInsertSteps ? (
            <Button
              variant="secondary"
              disabled={result.steps.length === 0}
              onClick={() => onInsertSteps(result.steps)}
            >
              Insert into Builder
            </Button>
          ) : (
            <p className="text-[11px] text-slate-500">
              Preview-only — open from Builder to insert steps directly.
            </p>
          )}
        </div>
      ) : null}
    </div>
  );
}
